package com.jordanaijordan.app;
import android.annotation.SuppressLint;import android.app.Activity;import android.content.Intent;import android.graphics.Color;import android.net.Uri;import android.os.Bundle;import android.os.Handler;import android.view.Gravity;import android.view.View;import android.view.Window;import android.webkit.*;import android.widget.*;import com.chaquo.python.PyObject;import com.chaquo.python.Python;
public class MainActivity extends Activity{
 private static final String URL="http://127.0.0.1:8765/"; private WebView web; private TextView status; private ProgressBar progress; private ValueCallback<Uri[]> upload; private final Handler h=new Handler();
 @SuppressLint("SetJavaScriptEnabled") public void onCreate(Bundle b){super.onCreate(b);requestWindowFeature(Window.FEATURE_NO_TITLE);getWindow().setStatusBarColor(Color.rgb(8,26,46));getWindow().setNavigationBarColor(Color.rgb(8,26,46));
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);
  LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(28,16,20,16);bar.setBackgroundColor(Color.rgb(8,26,46));
  TextView title=new TextView(this);title.setText("🇯🇴  Jordan AI");title.setTextColor(Color.WHITE);title.setTextSize(18);title.setTypeface(null,1);bar.addView(title,new LinearLayout.LayoutParams(0,-2,1));
  status=new TextView(this);status.setText("● تشغيل المحرك…");status.setTextColor(Color.rgb(214,168,79));bar.addView(status);root.addView(bar);
  progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);progress.setVisibility(View.GONE);root.addView(progress,new LinearLayout.LayoutParams(-1,4));
  web=new WebView(this);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);CookieManager.getInstance().setAcceptCookie(true);
  web.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){Uri u=r.getUrl();if("http".equals(u.getScheme())&&"127.0.0.1".equals(u.getHost()))return false;if("http".equals(u.getScheme())||"https".equals(u.getScheme())){try{startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(Exception ignored){}return true;}return false;}public void onPageStarted(WebView v,String u,android.graphics.Bitmap x){status.setText("● متصل");}public void onReceivedError(WebView v,WebResourceRequest r,WebResourceError e){status.setText("● خطأ");}});
  web.setWebChromeClient(new WebChromeClient(){public void onProgressChanged(WebView v,int p){progress.setVisibility(p<100?View.VISIBLE:View.GONE);progress.setProgress(p);}public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> cb,FileChooserParams q){upload=cb;try{startActivityForResult(q.createIntent(),501);return true;}catch(Exception e){upload=null;return false;}}});root.addView(web,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);startEngine();}
 private void startEngine(){new Thread(()->{try{Python py=Python.getInstance();PyObject m=py.getModule("android_server");m.callAttr("start_server",getFilesDir().getAbsolutePath());h.postDelayed(()->web.loadUrl(URL),350);}catch(Exception e){h.post(()->Toast.makeText(this,"فشل تشغيل Jordan AI: "+e.getMessage(),Toast.LENGTH_LONG).show());}}).start();}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==501&&upload!=null){Uri[] x=(c==RESULT_OK&&d!=null&&d.getData()!=null)?new Uri[]{d.getData()}:null;upload.onReceiveValue(x);upload=null;}}
 public void onBackPressed(){if(web.canGoBack())web.goBack();else super.onBackPressed();}
 protected void onDestroy(){if(web!=null){web.stopLoading();web.destroy();}super.onDestroy();}
}
